#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Values that aren't secret are remembered here for re-runs (outside the repo).
ENV_FILE="$HOME/.config/frames/r2.env"
mkdir -p "$(dirname "$ENV_FILE")"

BUCKET="frames"
DOMAIN="frames.devrobotics.dev"
REMOTE="frames-r2"

banner "Frames: Cloudflare R2 image hosting"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Enable R2"
say "Frames stores its photos in Cloudflare R2 (free up to 10 GB, no download fees)."
say "Open this link in your Mac's browser and log in to Cloudflare:"
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "In the left sidebar find Storage & databases → R2 Object Storage (or just R2)."
step "If R2 isn't enabled yet, follow 'Purchase R2 Plan' / 'Enable R2'."
note "Cloudflare asks for a payment method even for the free tier; you won't be charged under 10 GB."
pause "Press Enter once you can see the R2 Overview page"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the bucket"
step "On the R2 Overview page click 'Create bucket'."
step "Name: ${BUCKET}    Location: Automatic    Storage class: Standard. Click 'Create bucket'."
step "Go back to R2 Overview: the Account ID is shown in the right-hand panel (Account Details)."
note "It's a 32-character hex string. It isn't a secret."
ask R2_ACCOUNT_ID "Paste the Account ID:"
if [[ ! "$R2_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]]; then
	warn "That doesn't look like a 32-character Account ID; continuing anyway."
fi
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Connect ${DOMAIN}"
step "Open the '${BUCKET}' bucket → Settings tab → 'Custom Domains' → 'Connect Domain' (or '+ Add')."
step "Enter: ${DOMAIN}   then Continue → 'Connect domain'."
note "Cloudflare creates the DNS record for you because devrobotics.dev is on this account."
step "Wait until the domain's status shows 'Active' (usually under a minute; refresh the page)."
warn "Leave the 'r2.dev' public development URL disabled; the custom domain is the only public way in."
pause "Press Enter once ${DOMAIN} shows Active"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "CORS policy"
say "This lets pages on devrobotics.dev read the images from scripts (the lightbox),"
say "read-only, and nothing else."
step "Same bucket → Settings → 'CORS Policy' → 'Add CORS policy' (or Edit)."
step "Replace everything in the box with this JSON, then Save:"
printf '\n%s' "$DIM"
cat <<'JSON'
  [
    {
      "AllowedOrigins": ["https://devrobotics.dev", "https://www.devrobotics.dev"],
      "AllowedMethods": ["GET", "HEAD"],
      "AllowedHeaders": ["*"],
      "ExposeHeaders": ["Content-Length", "Content-Type", "ETag"],
      "MaxAgeSeconds": 86400
    }
  ]
JSON
printf '%s\n' "$RESET"
pause "Press Enter once the CORS policy is saved"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "API token for uploads"
step "Back on R2 Overview → 'Manage API tokens' (Account Details panel) → 'Create Account API token'"
note "(a User API token works too)."
step "Token name: frames-pi    Permissions: 'Object Read & Write'"
step "Specify bucket(s): Apply to specific buckets only → ${BUCKET}    TTL: Forever"
step "Click 'Create API Token'. The next page shows the keys ONCE: keep it open."
ask_secret R2_ACCESS_KEY_ID "Paste the Access Key ID (hidden):"
ask_secret R2_SECRET_ACCESS_KEY "Paste the Secret Access Key (hidden):"
if [[ -z "$R2_ACCESS_KEY_ID" || -z "$R2_SECRET_ACCESS_KEY" ]]; then
	warn "Both keys are needed. Re-run this wizard when you have them."
	exit 1
fi
note "These go only into rclone's config on this Pi, never into the repo or GitHub."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Configure rclone on the Pi"
command -v rclone >/dev/null 2>&1 || { warn "rclone is missing: run _tools/frames/setup.sh first."; exit 1; }
if rclone listremotes 2>/dev/null | grep -qx "${REMOTE}:"; then
	if confirm "A '${REMOTE}' remote already exists. Replace it?"; then
		rclone config delete "$REMOTE"
	else
		warn "Kept the existing remote; verification below uses it."
	fi
fi
if ! rclone listremotes 2>/dev/null | grep -qx "${REMOTE}:"; then
	rclone config create "$REMOTE" s3 \
		provider=Cloudflare \
		access_key_id="$R2_ACCESS_KEY_ID" \
		secret_access_key="$R2_SECRET_ACCESS_KEY" \
		endpoint="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
		# R2 returns object versions that rclone 1.60's post-upload check can't query (501)
		no_head=true \
		no_check_bucket=true >/dev/null
	printf '  %s✓ created%s rclone remote %s\n' "$GREEN" "$RESET" "$REMOTE"
fi
chmod 600 "$(rclone config file | tail -n1)"
unset R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify upload and public read"
probe="_wizard-check-$(date +%s).txt"
tmp=$(mktemp)
printf 'frames r2 ok %s\n' "$(date -Iseconds)" > "$tmp"
ok=1
if rclone copyto "$tmp" "${REMOTE}:${BUCKET}/${probe}" \
	--header-upload "Content-Type: text/plain; charset=utf-8" \
	--header-upload "Cache-Control: no-store" 2>/dev/null; then
	printf '  %s✓ uploaded%s %s\n' "$GREEN" "$RESET" "$probe"
else
	warn "Upload failed: check the token has Object Read & Write on '${BUCKET}' and the Account ID."
	ok=0
fi
if (( ok )); then
	body=""
	for _ in 1 2 3 4 5 6; do
		body=$(curl -fsS "https://${DOMAIN}/${probe}" 2>/dev/null || true)
		[[ -n "$body" ]] && break
		sleep 5
	done
	if [[ "$body" == "$(cat "$tmp")" ]]; then
		printf '  %s✓ read back%s https://%s/%s\n' "$GREEN" "$RESET" "$DOMAIN" "$probe"
		ctype=$(curl -fsSI "https://${DOMAIN}/${probe}" | tr -d '\r' | awk -F': ' 'tolower($1)=="content-type"{print $2}' || true)
		note "content-type: ${ctype:-?}"
	else
		warn "Couldn't read it from https://${DOMAIN}/ yet: is the custom domain Active?"
		ok=0
	fi
	rclone deletefile "${REMOTE}:${BUCKET}/${probe}" 2>/dev/null && note "test file deleted"
fi
rm -f "$tmp"
(( ok )) || SKIPPED+=("Fix the warning above, then re-run: _tools/frames/setup-r2.sh")
(( ok )) && note "Ready. Publish with: _tools/frames/frames.py publish"
pause "Press Enter for the summary"

finish
