"""HTML for frames.html (between markers) and story pages."""
import datetime as dt
import json
import re

from .md import esc

SITE = 'https://devrobotics.dev'
GENERATED = '<!-- Generated by _tools/frames from the Frames Inbox. Do not edit by hand: change the Inbox and run build. -->'
PIN = '<svg class="pin" viewBox="0 0 24 24" width="12" height="12" aria-hidden="true" focusable="false"><path d="M12 22s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="10" r="2.5" fill="currentColor"/></svg>'
BADGE = '<span class="frame-tile__badge" aria-hidden="true"><svg viewBox="0 0 24 24" width="20" height="20"><path d="M12 6.5C10.3 5.2 7.9 4.5 4.5 4.5H3v13h1.5c3.4 0 5.8.7 7.5 2 1.7-1.3 4.1-2 7.5-2H21v-13h-1.5c-3.4 0-5.8.7-7.5 2z"/><path d="M12 6.5v13.5"/></svg><span class="frame-tile__badge-label">Story</span></span>'


class RenderError(Exception):
	pass


def plural(n, one, many):
	return f'{n} {one if n == 1 else many}'


def stats_html(counts):
	parts = [plural(counts['photos'], 'photo', 'photos'), plural(counts['stories'], 'story', 'stories')]
	if counts['places']:
		parts.append(plural(counts['places'], 'place', 'places'))
	ys = counts.get('years') or []
	if ys:
		parts.append(str(ys[0]) if ys[0] == ys[1] else f'{ys[0]}–{ys[1]}')
	return f'<p class="frames-stats mono">{esc(" · ".join(parts))}</p>'


def u(base, path):
	return esc(f'{base}/{path}')


def tile_img(base, src, alt, slug, idx):
	load = 'loading="eager" fetchpriority="high"' if idx == 0 else 'loading="eager"' if idx < 3 else 'loading="lazy"'
	return (f'<img src="{u(base, src["sq480"])}" srcset="{u(base, src["sq480"])} 480w, {u(base, src["sq960"])} 960w" '
		f'sizes="(min-width: 1248px) 400px, 33vw" width="960" height="960" alt="{esc(alt)}" {load} decoding="async" '
		f'style="view-transition-name: frame-{esc(slug)}" />')


def grid_html(items, base, indent=''):
	t = indent + '\t'
	lines = ['<ul class="frames-grid" role="list">']
	for i, it in enumerate(items):
		if it['type'] == 'photo':
			lines.append(f'{t}<li><a class="frame-tile" href="#{esc(it["slug"])}" data-slug="{esc(it["slug"])}" data-type="photo">')
			lines.append(f'{t}\t{tile_img(base, it["src"], it["alt"], it["slug"], i)}')
			lines.append(f'{t}\t<span class="frame-tile__meta"><span class="frame-tile__note">{esc(it["note"])}</span><span class="frame-tile__place mono">{PIN} {esc(it["place"])} · {it["year"]}</span></span>')
		else:
			c = it['cover']
			lines.append(f'{t}<li><a class="frame-tile frame-tile--story" href="frames/{esc(it["slug"])}.html" data-slug="{esc(it["slug"])}" data-type="story">')
			lines.append(f'{t}\t{tile_img(base, c["src"], c["alt"], it["slug"], i)}')
			lines.append(f'{t}\t{BADGE}')
			lines.append(f'{t}\t<span class="frame-tile__meta"><span class="frame-tile__note">{esc(it["summary"] or it["title"])}</span><span class="frame-tile__place mono">Story · {it["readMinutes"]} min read</span></span>')
		lines.append(f'{t}</a></li>')
	lines.append(f'{indent}</ul>')
	return '\n'.join(lines)


def fill_markers(page: str, name: str, content: str, path_label='frames.html') -> str:
	start, end = f'<!-- frames:{name} -->', f'<!-- /frames:{name} -->'
	if page.count(start) != 1 or page.count(end) != 1:
		raise RenderError(f'{path_label} must contain exactly one "{start}" and one "{end}" (found {page.count(start)} and {page.count(end)})')
	a = page.index(start) + len(start)
	b = page.index(end)
	if b < a:
		raise RenderError(f'{path_label}: "{end}" comes before "{start}"')
	line_start = page.rfind('\n', 0, page.index(start)) + 1
	indent = re.match(r'[ \t]*', page[line_start:]).group(0)
	if callable(content):
		content = content(indent)
	return page[:a] + '\n' + indent + content + '\n' + indent + page[b:]


# --- story ----------------------------------------------------------------

def _figure(base, p, idx, place, extra_class='', sizes='(min-width: 1248px) 1200px, 100vw', note=''):
	s = p['src']
	where = p.get('place') or place
	rest = esc(' · '.join(x for x in (where, p['shot'].get('aperture'), p['shot'].get('shutter')) if x))
	meta_html = f'{PIN} {rest}' if where else rest
	cls = 'story-figure' + (f' {extra_class}' if extra_class else '')
	note_html = f'<span class="story-figure__note">{esc(note)}</span>' if note else ''
	return (f'<figure class="{cls}" data-photo-index="{idx}" style="--ar: {p["width"]}/{p["height"]}"><button class="story-figure__open" type="button" aria-label="Open photo: {esc(p["alt"])}">'
		f'<img src="{u(base, s["w1280"])}" srcset="{u(base, s["w1280"])} 1280w, {u(base, s["w2560"])} 2560w" sizes="{sizes}" '
		f'width="{p["width"]}" height="{p["height"]}" alt="{esc(p["alt"])}" loading="lazy" decoding="async" /></button>'
		f'<figcaption>{note_html}<span class="story-figure__meta mono">{meta_html}</span></figcaption></figure>')


def story_body(blocks, base, place, photo_index, photos, clips, md_render):
	"""blocks: [('md', html) | ('marker', Marker)] already rendered md."""
	out = []
	for kind, b in blocks:
		if kind == 'md':
			out.append(b)
			continue
		mk = b
		if mk.kind == 'image':
			i = photo_index[mk.files[0]]
			cls = 'story-figure--full' if mk.full else ''
			sizes = '100vw' if mk.full else '(min-width: 1248px) 1200px, 100vw'
			out.append(_figure(base, photos[i], i, place, cls, sizes, mk.note))
		elif mk.kind == 'images':
			n = len(mk.files)
			sizes = '(min-width: 1248px) 600px, 50vw' if n == 2 else '(min-width: 1248px) 400px, 33vw'
			figs = ''.join(_figure(base, photos[photo_index[f]], photo_index[f], place, 'story-figure--row', sizes, photos[photo_index[f]]['note']) for f in mk.files)
			out.append(f'<div class="story-row story-row--{n}">{figs}</div>')
		elif mk.kind == 'clip':
			c = clips[mk.files[0]]
			label = mk.note or 'Clip'
			cap = f'<figcaption>{esc(mk.note)}</figcaption>' if mk.note else ''
			out.append(f'<figure class="story-clip" style="--ar: {c["width"]}/{c["height"]}"><video src="{u(base, c["mp4"])}" poster="{u(base, c["poster"])}" width="{c["width"]}" height="{c["height"]}" '
				f'muted loop playsinline controls preload="none" aria-label="{esc(label)}"></video>{cap}</figure>')
		elif mk.kind == 'youtube':
			vid, title = mk.yt_id, mk.note or 'YouTube video'
			out.append(f'<figure class="story-video yt-embed" data-id="{esc(vid)}" data-title="{esc(title)}"><a href="https://www.youtube.com/watch?v={esc(vid)}" target="_blank" rel="noopener">'
				f'<img src="https://i.ytimg.com/vi/{esc(vid)}/hqdefault.jpg" alt="" loading="lazy" width="480" height="360" /><span class="yt-embed__play" aria-hidden="true"></span>'
				f'<span class="yt-embed__title">{esc(title)}</span></a></figure>')
	return '\n'.join(out)


def cover_html(base, story):
	c = story['cover']
	s = c['src']
	return (f'<img class="story-hero__img" src="{u(base, s["w2560"])}" srcset="{u(base, s["w1280"])} 1280w, {u(base, s["w2560"])} 2560w" sizes="100vw" '
		f'width="{c["width"]}" height="{c["height"]}" alt="{esc(c["alt"])}" fetchpriority="high" style="view-transition-name: frame-{esc(story["slug"])}" data-photo-index="0" />')


def pager_html(base, nxt):
	h = '<nav class="story-pager" aria-label="More from Frames"><a class="story-pager__back" href="/frames.html">← Back to Frames</a>'
	if nxt:
		h += (f'<a class="story-pager__next" href="/frames/{esc(nxt["slug"])}.html"><img src="{u(base, nxt["cover"]["src"]["sq480"])}" alt="" width="96" height="96" loading="lazy" />'
			f'<span><span class="eyebrow">Next story</span><span>{esc(nxt["title"])}</span></span></a>')
	return h + '</nav>'


def date_display(iso):
	d = parse_iso(iso)
	return d.strftime('%B %Y') if d else ''


def parse_iso(iso):
	if not iso:
		return None
	try:
		return dt.datetime.fromisoformat(iso)
	except ValueError:
		return None


def json_for_script(obj):
	return json.dumps(obj, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/').replace('<!--', '<\\!--')


def abs_media(base, path):
	return f'{base}/{path}' if re.match(r'^https?://', base) else f'{SITE}{base}/{path}'


def story_page(template, story, base, body, nxt, meta_description):
	vals = {
		'title': esc(story['title']),
		'place': esc(story['place']),
		'date_display': esc(date_display(story['date'])),
		'date_iso': esc(story['date']),
		'read_minutes': str(story['readMinutes']),
		'summary': esc(story['summary']),
		'meta_description': esc(meta_description),
		'canonical': esc(f'{SITE}/frames/{story["slug"]}.html'),
		'og_image': esc(abs_media(base, story['cover']['src']['w1280'])),
		'slug': esc(story['slug']),
		'cover_html': cover_html(base, story),
		'body_html': body,
		'pager_html': pager_html(base, nxt),
		'photos_json': json_for_script(story['photos']),
		'media_base': esc(base),
	}
	out = re.sub(r'\{\{([a-z_]+)\}\}', lambda m: vals[m.group(1)] if m.group(1) in vals else m.group(0), template)
	left = sorted(set(re.findall(r'\{\{[^}]*\}\}', template)) - {'{{%s}}' % k for k in vals})
	if left:
		raise RenderError(f'story template has unknown placeholders: {", ".join(left)}')
	m = re.match(r'(\s*<!doctype[^>]*>)', out, re.I)
	if m:
		out = out[:m.end()] + '\n' + GENERATED + out[m.end():]
	else:
		out = GENERATED + '\n' + out
	return out
